<div class="navbar navbar-default navbar-fixed-bottom dt-footer">
    <div class="container">
        <?php
        function isMobileDevice()
        {
            $aMobileUA = array(
                '/iphone/i' => 'iPhone',
                '/ipod/i' => 'iPod',
                '/ipad/i' => 'iPad',
                '/android/i' => 'Android',
                '/blackberry/i' => 'BlackBerry',
                '/webos/i' => 'Mobile'
            );

            //Return true if Mobile User Agent is detected
            foreach ($aMobileUA as $sMobileKey => $sMobileOS) {
                if (preg_match($sMobileKey, $_SERVER['HTTP_USER_AGENT'])) {
                    return true;
                }
            }
            //Otherwise return false..
            return false;
        }

        ?>
        <?php if (isMobileDevice()): ?>
            <a href="/debts/add" class="navbar-btn btn-success btn pull-right">Create a new debt</a>
        <?php else: ?>
            <!-- Trigger the modal with a button -->
            <button type="button" class="navbar-btn btn-success btn pull-right" data-toggle="modal" data-target="#myModal">Open Modal</button>

            <!-- Modal -->



        <?php endif; ?>
    </div>
</div>





<!--<div class = "modal fade" id ="selectcontacts">-->
<!--    <div class = "modal-dialog">-->
<!--        <div class = "modal-content">-->
<!--            <div class = "modal-header">-->
<!--                <h3>Create a debt...</h3>-->
<!--            </div>-->
<!--            <div class = "modal-body">-->
<!--                --><?php
//                include "debtcreator.php";
//                ?>
<!--            </div>-->
<!--            <div class="modal-footer">-->
<!--                <div class="buttons">-->
<!--                    <a href = "#selectcontacts" class = "navbar-btn btn-danger btn pull-left" data-toggle="modal">Cancel</a>-->
<!--                    <div id="debtnext" class = "navbar-btn btn-success btn pull-right">Next ></div>-->
<!--                    <div id="debtprevious" class = "navbar-btn btn-danger btn pull-right hidden">< Go Back</div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <script src = "src/assets/js/debtcreator.js"></script>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
