<h2>Debts you owe:</h2>
<div class="table-responsive">
    <table class="table">
        <colgroup>
            <col span="1" style="width: 20%;">
            <col span="1" style="width: 35%;">
            <col span="1" style="width: 20%;">
            <col span="1" style="width: 25%;">
        </colgroup>
        <thead>
        <tr>
            <th></th>
            <th>Name</th>
            <th>Amount</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($debtTable as $debt): ?>
            <tr>
                <td><div class="expand" id="dd<?= $debt->email ?>">[+]</div></td>
                <td><?= $debt->name ?></td>
                <td><?= $debt->amount ?></td>
                <td><a href='paydebtconfirm.php?debt0=<?= $debt->uid ?>' class='btn btn-warning'>Pay Now</a></td>
            </tr>
            <tr class='detailedDebt dd<?= $debt->email ?> hidden'>
                <td>Date Created</td><td>Description</td><td></td><td>Amount</td>
            </tr>
            <?php foreach ($debt->activeDebts as $activeDebt): ?>
                <tr class='detailedDebt dd<?= $debt->email ?> hidden'>
                    <td><?= $activeDebt->dateCreated ?></td>
                    <td colspan='2'><? $activeDebt->description ?></td>
                    <td><?= $activeDebt->amount ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>