<div class = "navbar navbar-inverse navbar-static-top">
    <div class = "container">
        <div class="navbar-header">
            <a href = "#" class = "navbar-brand">
                <?php if(array_key_exists('user',$_SESSION)): ?>
                    Hello <?= $_SESSION['user']['name'] ?>
                <?php else: ?>
                    Debt Tennis Tracker
                <?php endif ?>
            </a>

            <button class="navbar-toggle" data-toggle="collapse" data-target="#navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class = "collapse navbar-collapse" id="navHeaderCollapse">
            <ul class = "nav navbar-nav navbar-right">
            <?php if(array_key_exists('user',$_SESSION)) : ?>
                <?php
                    $links = [
                        'View Debts' => '/debts/view',
                        'Your Contacts' => '/user/contacts',
                        'Logout' => '/user/logout'
                    ];
                ?>
                <?php foreach ($links as $string => $link) : ?>
                    <li class="<?php echo ($_SERVER['REQUEST_URI'] == $link) ?  'active' : '' ; ?>">
                        <a href="<?= $link ?>"><?= $string ?></a>
                    </li>
                <?php endforeach; ?>

            <?php else :
                echo '	<form class="navbar-form navbar-right" action="user/login" method="POST">
								<div class="form-group">
									<input type="text" name="email" class="form-control" placeholder="Email">
									<input type="password" name="password" class="form-control" placeholder="Password">
								</div>
								<button type="submit" class="btn btn-default">Login</button>
								<a href="/forgottenyourpassword">Forgotten your password?</a>
							</form>';
            endif;
            ?>
        </div>
    </div>
</div>