<div class = "navbar navbar-inverse navbar-static-top">
    <div class = "container">
        <div class="navbar-header">
            <a href = "#" class = "navbar-brand">
                <?php if(array_key_exists('uid',$_SESSION)): ?>
                    Hello <? $_SESSION['name'] ?>
                <?php else: ?>
                    Debt Tennis Tracker
                <?php endif ?>
            </a>

            <button class="navbar-toggle" data-toggle="collapse" data-target="#navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class = "collapse navbar-collapse" id="navHeaderCollapse">
            <ul class = "nav navbar-nav navbar-right">
            <?php if(array_key_exists('uid',$_SESSION)) : ?>
                <?php
                    $links = [
                        'profile.php',
                        'contacts.php',
                        'logout.php'
                    ];
                    foreach ($links as $link) {
                        if (strpos($_SERVER["PHP_SELF"], $link) !== false) : ?>
                        <li class="active"><a
                                href="../../app/models/<?= $link ?>"><?= ucfirst(substr($link, 0, strlen($link) - 4)) ?></a>
                        </li>
                        <?php endif;
                    }

            else :
                echo '	<form class="navbar-form navbar-right" action="../../app/models/loginsubmit.php" method="POST">
								<div class="form-group">
									<input type="text" name="email" class="form-control" placeholder="Email">
									<input type="password" name="password" class="form-control" placeholder="Password">
								</div>
								<button type="submit" class="btn btn-default">Login</button>
							</form>';
            endif;
            ?>
        </div>
    </div>
</div>