<?php
$this->layout('layouts::default', ['title' => $title])
?>
<div class="mainpage">
    <table id ='debttable'>
        <form action="/forgottenyourpassword" method="POST">
            <tr>
                <td>Email of the account to have password changed</td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr>
                <td>New password</td>
                <td><input type="password" name="password"></td>
            </tr>
            <tr><td></td><td><input type="submit" value="Change Password"></td></tr>
        </form>
    </table>
</div>