<?php
$this->layout('layouts::default', ['title' => $title])
?>

<div class = "container">
    <div class = "row">
        <div class = "col-md-6">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="5000" data-pause="hover">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="../../../resources/images/homepageimage1.png" alt="Your own personal debt tracking tool">
                    </div>
                    <div class="item">
                        <img src="../../../resources/images/homepageimage2.png" alt="Get detailed information at a glance">
                    </div>
                    <div class="item">
                        <img src="../../../resources/images/homepageimage3.png" alt="Easily create debts">
                    </div>
                </div>
            </div>
        </div>

        <div class = "col-md-6">
            <?php $this->insert('partials::register', []) ?>
        </div>
    </div>
</div>
