<?php
    $this->layout('layouts::default', ['title' => $title, 'user' => $user, 'contacts' => $contacts]);
?>

<div class="container">
    <div class="jumbotron">
        <h2>Debts For Contacts:</h2>
        <div class="dt-contact-debt-table-column dt-contact-debt-table-head">
            <div>Contact Name</div>
            <div>Amount:</div>
            <div>Action:</div>
        </div>
        <div class="dt-contact-debt-table">
            <?php foreach ($contactDebts as $contactDebt) : ?>
            <div class="dt-contact-debt-table-column">
                <div><?= $contactDebt['name'] ?></div>
                <div><?= $contactDebt['amount'] ?></div>
                <div><?= ($contactDebt['amount'] > 0) ? "Send Reminder" : "Pay Now" ?></div>
            </div>
            <?php endforeach; ?>
        </div>
        <div style="clear:both;"></div>
    </div>
</div>

<div class = "container">
    <div class = "row">
        <div class = "col-md-6">
            <?php $this->insert('partials::debt-table', [
                'debts' => $debtsOwedToYou,
                'tableTitle' => 'Debts Owed To You',
                'tableAmount' => 'Amount You\'re Owed',
                'tableClass' => 'warning',
                'tableAction' => '/debts/sendreminder/',
                'tableActionString' => 'Send Reminder',
            ]) ?>
        </div>
        <div class = "col-md-6">
            <?php $this->insert('partials::debt-table', [
                'debts' => $debtsYouOwe,
                'tableTitle' => 'Debts You Owe',
                'tableAmount' => 'Amount You Owe',
                'tableClass' => 'danger',
                'tableAction' => '/debts/pay/',
                'tableActionString' => 'Pay Now',
            ]) ?>
        </div>
    </div>
</div>

<script type="module" module-name="DebtCreator">
    import DebtCreator from "/src/assets/es6/Modules/DebtCreator"
    let debtCreator = new DebtCreator();
    debtCreator.init();
</script>

<div id="myModal" class="modal fade dt-modal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content" style="height: 500px;">
            <div class="modal-header" style="display: none;">
            </div>
            <div class="modal-body" style="height: 100%; padding: 0;">
                <?php $this->insert("partials::DebtCreator/add-debt", ["user" => $user, "contacts" => $contacts]); ?>
            </div>
            <div class="modal-footer" style="display: none;">
            </div>
        </div>

    </div>
</div>



<script>
    $(window).on('load', function(){
        $('.dt-debt-table-expand-section').hide();
        $('.dt-debt-table-expand').on('click', function() {
            $('.dt-debt-table-expand-section[data-value="' + $(this).attr('data-value') + '"').slideToggle();
        });
    });
</script>



    <link href="/src/assets/css/add-debt.css" rel="stylesheet" type="text/css" />