<div class="dt-create-debt__container" data-value="Choose Debt" hide-controls="true">
    <div class="dt-create-debt__content">
        <div class="dt-create-debt__content--instructions">
            <h2>Please select a debt type</h2>
        </div>
        <div class="dt-create-debt__split-content">
            <div class="dt-create-debt__split-content dt-create-debt__split-content--container dt-create-debt__split-content--right" action="/debts/create">
                <div class="dt-create-debt__split-content--text">
                    <h2>Single Debt</h2>
                    <p>Create a debt between you and one other person.</p>
                </div>
            </div>
            <div class="dt-create-debt__split-content dt-create-debt__split-content--container dt-create-debt__split-content--right" action="/debts/create-multi">
                <div class="dt-create-debt__split-content--text">
                    <h2>Split Debt</h2>
                    <p>Create a debt between you and a group of people split evenly between you.</p>
                </div>
            </div>
        </div>
    </div>
</div>