<div class="dt-create-debt__container" data-value="Add a description">
    <div class="dt-create-debt__content">
        <div class="dt-create-debt__content--instructions">
            <h2>Add a description for the debt</h2>
            <h4>
                Enter a helpful description to help you remember
                what the debt is about. You don't have to
                enter a description.
            </h4>
        </div>
        <div class="dt-create-debt__input">
            <label>Description:</label>
            <textarea class="dt-create-debt__description"></textarea>
        </div>
    </div>
</div>